StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{596C270A7B3A77A8}" {
   Id "VME-AmmunitionID_762x25mm"
   Target_en_us "762x25mm"
   Target_fr_fr "762 × 25 mm"
   Target_it_it "762x25 mm"
   Target_de_de "762 × 25 mm"
   Target_es_es "762x25 mm"
   Target_cs_cz "762 × 25mm"
   Target_pl_pl "762 × 25 mm"
   Target_ru_ru "762x25 мм"
   Target_ja_jp "762x25mm"
   Target_ko_kr "762x25mm"
   Target_pt_br "762x25mm"
   Target_zh_cn "762x25 毫米"
   Comment "Caliber of ammuntion used by e.g. QSZ-54"
   Status TRANSLATION_DONE
   Modified 1500267945
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1000
   }
  }
  CustomStringTableItem "{5966A779C355A320}" {
   Id "VME-Magazine_QBB81_Description"
   Target_en_us "Magazine loaded with DBP-56 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DBP-56 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio Target Fr Fr."
   Target_de_de "Magazin mit DBP-56-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DBP-56 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DBP-56 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DBP-56 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DBP-56."
   Target_ja_jp "DBP-56 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DBP-56 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DBP-56 de núcleo de aço."
   Target_zh_cn "装有 DBP-56 钢芯弹的弹鼓。"
   Comment "Inventory tooltip for the 45 round 7.62x39mm QBB-81 magazine with steel core cartridges"
   Status TRANSLATION_DONE
   Modified 1500267942
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{C3D2AD00703A9B2E}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBB81_75rnd_Base.et"
  }
  CustomStringTableItem "{5966A77A1DAE8268}" {
   Id "VME-Magazine_QBB81_Name"
   Target_en_us "7.62×39mm 75rnd QBB-81 Mag"
   Target_fr_fr "Chargeur 75 balles QBB-81 7,62 × 39 mm"
   Target_it_it "Caricatore QBB-81 75 colpi 7,62×39 mm"
   Target_de_de "75-Schuss-QBB-81-Magazin. Kaliber 7,62 × 39 mm."
   Target_es_es "Cargador de QBB-81 de 7,62×39 mm, 75 p."
   Target_cs_cz "Zásobník QBB-81, 7,62 × 39 mm, 75 ran"
   Target_pl_pl "75-nab. magazynek 7,62 × 39 mm (QBB-81)"
   Target_ru_ru "Магазин для РПК-74, 75 патр., 7,62×39 мм"
   Target_ja_jp "7.62×39mm 75rnd QBB-81 マガジン"
   Target_ko_kr "7.62×39mm 75발 QBB-81 탄창"
   Target_pt_br "Carregador QBB-81 c/ 75 mun. 7.62×39mm"
   Target_zh_cn "7.62×39 毫米 75 发 QBB-81 弹鼓"
   Comment "UI display name of the 75 round QBB-81 magazine, using 7.62x39mm cartridges"
   Status TRANSLATION_DONE
   Modified 1500267940
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{C3D2AD00703A9B2E}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBB81_75rnd_Base.et"
  }
  CustomStringTableItem "{5966103FC4CF323C}" {
   Id "VME-Magazine_QBZ81_Description"
   Target_en_us "Magazine loaded with DBP-56 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DBP-56 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio DBP-56."
   Target_de_de "Magazin mit DBP-56-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DBP-56 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DBP-56 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DBP-56 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DBP-56."
   Target_ja_jp "DBP-56 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DBP-56 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DBP-56 de núcleo de aço."
   Target_zh_cn "装有 DBP-56 钢芯弹的弹匣。"
   Comment "Inventory tooltip for the default QBZ-81 magazine"
   Status TRANSLATION_DONE
   Modified 1500267937
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{2DB9F84FEAA5C7EA}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBZ81_30rnd_Base.et"
  }
  CustomStringTableItem "{5966103C66759F41}" {
   Id "VME-Magazine_QBZ81_Name"
   Target_en_us "7.62×39mm 30rnd QBZ-81 Mag"
   Target_fr_fr "Chargeur 30 balles QBZ-81 7,62 × 39 mm"
   Target_it_it "Caricatore QBZ-81 30 colpi 7,62×39 mm"
   Target_de_de "30-Schuss-QBZ-81-Magazin. Kaliber 7,62 × 39 mm."
   Target_es_es "Cargador de QBZ-81 de 7,62×39 mm, 30 p."
   Target_cs_cz "Zásobník QBZ-81, 7,62 × 39 mm, 30 ran"
   Target_pl_pl "30-nab. magazynek 7,62 × 39 mm (QBZ-81)"
   Target_ru_ru "Магазин для QBZ-81 на 30 патр., 7,62×39 мм"
   Target_ja_jp "7.62×39mm 30rnd QBZ-81 マガジン"
   Target_ko_kr "7.62×39mm 30발 QBZ-81 탄창"
   Target_pt_br "Carregador QBZ-81 c/ 30 mun. 7.62×39mm"
   Target_zh_cn "7.62×39 毫米 30 发 QBZ-81 弹匣"
   Comment "UI display name of the 30 round QBZ-81 magazine, using 7.62x39mm cartridges"
   Status TRANSLATION_DONE
   Modified 1500267934
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{2DB9F84FEAA5C7EA}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBZ81_30rnd_Base.et"
  }
  CustomStringTableItem "{596C270A2931476B}" {
   Id "VME-Magazine_QSZ54_Description"
   Target_en_us "Magazine loaded with DAP-51 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DAP-51 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio DAP-51."
   Target_de_de "Magazin mit DAP-51-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DAP-51 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DAP-51 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DAP-51 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DAP-51."
   Target_ja_jp "DAP-51 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DAP-51 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DAP-51 de núcleo de aço."
   Target_zh_cn "装有 DAP-51 钢芯弹的弹匣。"
   Comment "Inventory tooltip for the QSZ-54 pistol magazine"
   Status TRANSLATION_DONE
   Modified 1500267932
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
  }
  CustomStringTableItem "{596C270AD5E355FA}" {
   Id "VME-Magazine_QSZ54_Name"
   Target_en_us "762x25mm 8rnd QSZ-54 Mag"
   Target_fr_fr "Chargeur 8 balles QSZ-54 762 × 25 mm"
   Target_it_it "Caricatore QSZ-54 8 colpi 762x25 mm"
   Target_de_de "8-Schuss-QSZ-54-Magazin. Kaliber 762 × 25 mm."
   Target_es_es "Cargador de QSZ-54 de 762x25 mm, 8 p."
   Target_cs_cz "Zásobník QSZ-54, 762 × 25 mm, 8 ran"
   Target_pl_pl "8-nab. magazynek 762 × 25 mm (QSZ-54)"
   Target_ru_ru "Магазин для QSZ-54, 8 патр., 762x25 мм"
   Target_ja_jp "762x25mm 8rnd QSZ-54 マガジン"
   Target_ko_kr "762x25mm 8발 QSZ-54 탄창"
   Target_pt_br "Carregador QSZ-54 c/ 8 mun. 762x25mm"
   Target_zh_cn "762x25 毫米 8 发 QSZ-54 弹匣"
   Comment "UI display name of the 8 round 762x25mm QSZ-54 pistol magazine"
   Status TRANSLATION_DONE
   Modified 1500267929
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{98EA3A7DB57F989F}Prefabs/Weapons/Magazines/VME_Magazine_762x25_QSZ54_8rnd_Base.et"
  }
  CustomStringTableItem "{5966A77EA8EBE3B2}" {
   Id "VME-Weapon_QBB81_Description"
   Target_en_us "7.62×39mm light machine gun."
   Target_fr_fr "Mitrailleuse légère 7,62 × 39 mm."
   Target_it_it "Mitragliatrice leggera da 7,62×39 mm."
   Target_de_de "Leichtes Maschinengewehr im Kaliber 7,62 × 39 mm."
   Target_es_es "Ametralladora ligera de 7,62×39 mm."
   Target_cs_cz "Lehký kulomet ráže 7,62 × 39 mm."
   Target_pl_pl "Lekki karabin maszynowy 7,62 × 39 mm."
   Target_ru_ru "Легкий пулемет 7,62×39 мм."
   Target_ja_jp "7.62×39mm 軽機関銃。"
   Target_ko_kr "7.62×39mm 경기관총."
   Target_pt_br "Metralhadora leve 7.62×39mm."
   Target_zh_cn "7.62×39mm 班用机枪。"
   Status TRANSLATION_DONE
   Modified 1500267927
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{D00F9E62E98B41BB}Prefabs/Weapons/MachineGuns/QBB81/VME_MG_QBB81.et"
  }
  CustomStringTableItem "{5966A77EB61DCAB5}" {
   Id "VME-Weapon_QBB81_Name"
   Target_en_us "QBB-81"
   Target_fr_fr "QBB-81"
   Target_it_it "QBB-81"
   Target_de_de "QBB-81"
   Target_es_es "QBB-81"
   Target_cs_cz "QBB-81"
   Target_pl_pl "QBB-81"
   Target_ru_ru "QBB-81"
   Target_ja_jp "QBB-81"
   Target_ko_kr "QBB-81"
   Target_pt_br "QBB-81"
   Target_zh_cn "QBB-81"
   Comment "Designation of the QBB-81"
   Status TRANSLATION_DONE
   Modified 1500267924
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{D00F9E62E98B41BB}Prefabs/Weapons/MachineGuns/QBB81/VME_MG_QBB81.et"
  }
  CustomStringTableItem "{5966103997F423F1}" {
   Id "VME-Weapon_QBZ81-1_Description"
   Target_en_us "7.62×39mm assault rifle."
   Target_fr_fr "Fusil d'assaut de calibre 7,62 × 39 mm."
   Target_it_it "Fucile d’assalto da 7,62×39 mm."
   Target_de_de "Sturmgewehr im Kaliber 7,62 × 39 mm."
   Target_es_es "Fusil de asalto de 7,62×39 mm."
   Target_cs_cz "Útočná puška ráže 7,62 × 39 mm."
   Target_pl_pl "Karabinek automatyczny 7,62 × 39 mm."
   Target_ru_ru "Штурмовая винтовка 7,62×39 мм."
   Target_ja_jp "7.62×39mm アサルトライフル。"
   Target_ko_kr "7.62×39mm 돌격소총."
   Target_pt_br "Fuzil de assalto 7.62×39mm."
   Target_zh_cn "7.62×39mm 自动步枪。"
   Comment "Inventory tooltip for the QBZ-81 assault rifle - caliber and weapon type"
   Status TRANSLATION_DONE
   Modified 1500267921
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{E4672CFB06A4E556}Prefabs/Weapons/Rifles/QBZ81/VME_Rifle_QBZ81-1.et"
  }
  CustomStringTableItem "{59661039B274A3A6}" {
   Id "VME-Weapon_QBZ81-1_Name"
   Target_en_us "QBZ-81-1"
   Target_fr_fr "QBZ-81-1"
   Target_it_it "QBZ-81-1"
   Target_de_de "QBZ-81-1"
   Target_es_es "QBZ-81-1"
   Target_cs_cz "QBZ-81-1"
   Target_pl_pl "QBZ-81-1"
   Target_ru_ru "QBZ-81-1"
   Target_ja_jp "QBZ-81-1"
   Target_ko_kr "QBZ-81-1"
   Target_pt_br "QBZ-81-1"
   Target_zh_cn "QBZ-81-1"
   Comment "Designation of the QBZ81-1 assault rifle, will serve as a display name in the UI"
   Status TRANSLATION_DONE
   Modified 1500267918
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{E4672CFB06A4E556}Prefabs/Weapons/Rifles/QBZ81/VME_Rifle_QBZ81-1.et"
  }
 }
}