StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{596C270A7B3A77A8}" {
   Id "VME-AmmunitionID_762x25mm"
   Target_en_us "762x25mm"
   Target_fr_fr "762 × 25 mm"
   Target_it_it "762x25 mm"
   Target_de_de "762 × 25 mm"
   Target_es_es "762x25 mm"
   Target_cs_cz "762 × 25mm"
   Target_pl_pl "762 × 25 mm"
   Target_ru_ru "762x25 мм"
   Target_ja_jp "762x25mm"
   Target_ko_kr "762x25mm"
   Target_pt_br "762x25mm"
   Target_zh_cn "762x25 毫米"
   Comment "Caliber of ammuntion used by e.g. QSZ-54"
   Status TRANSLATION_DONE
   Modified 1500267945
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1000
   }
  }
  CustomStringTableItem "{5978D67E0A4AE8B6}" {
   Id "VME-Faction_PRC"
   Target_en_us "Chinese People's Liberation Army"
   Target_fr_fr "Armée populaire de libération chinoise"
   Target_it_it "Esercito popolare di liberazione cinese"
   Target_de_de "Chinesische Volksbefreiungsarmee"
   Target_es_es "Ejército Popular de Liberación de China"
   Target_cs_cz "Čínská lidová osvobozenecká armáda"
   Target_pl_pl "Chińska Armia Ludowo-Wyzwoleńcza"
   Target_ru_ru "Народно-освободительная армия Китая"
   Target_ja_jp "中国人民解放軍"
   Target_ko_kr "중국 인민해방군"
   Target_pt_br "Exército de Libertação do Povo Chinês"
   Target_zh_cn "中国人民解放军"
   Comment "Faction name."
   Status TRANSLATION_DONE
   Modified 1501095599
   Author "huhao"
   LastChanged "huhao"
   Labels {
    0 600
   }
  }
  CustomStringTableItem "{5978D67E4CE6EC71}" {
   Id "VME-Faction_PRC-UC"
   Target_en_us "CHINESE PEOPLE'S LIBERATION ARMY"
   Target_fr_fr "ARMÉE POPULAIRE DE LIBÉRATION CHINOISE"
   Target_it_it "ESERCITO POPOLARE DI LIBERAZIONE CINESE"
   Target_de_de "CHINESISCHE VOLKSBEFREIUNGSARMEE"
   Target_es_es "EJÉRCITO POPULAR DE LIBERACIÓN DE CHINA"
   Target_cs_cz "ČÍNSKÁ LIDOVÁ OSVOBOZENECKÁ ARMÁDA"
   Target_pl_pl "CHIŃSKA ARMIA LUDOWO-WYZWOLEŃCZA"
   Target_ru_ru "НАРОДНО-ОСВОБОДИТЕЛЬНАЯ АРМИЯ КИТАЯ"
   Target_ja_jp "中国人民解放軍"
   Target_ko_kr "중국 인민해방군"
   Target_pt_br "EXÉRCITO DE LIBERTAÇÃO DO POVO CHINÊS"
   Target_zh_cn "中国人民解放军"
   Comment "Faction name."
   Status TRANSLATION_DONE
   Modified 1501095416
   Author "huhao"
   LastChanged "huhao"
   Labels {
    0 600
   }
  }
  CustomStringTableItem "{5978D671945456A8}" {
   Id "VME-Faction_PRC_Short"
   Target_en_us "China"
   Target_fr_fr "Cina"
   Target_it_it "China"
   Target_de_de "Porcelana"
   Target_es_es "Čína"
   Target_cs_cz "Chiny"
   Target_pl_pl "Target Cs Cz"
   Target_ru_ru "Китай"
   Target_ja_jp "中国"
   Target_ko_kr "중국"
   Target_pt_br "China"
   Target_zh_cn "中国"
   Comment "Faction name."
   Status TRANSLATION_DONE
   Modified 1501099904
   Author "huhao"
   LastChanged "huhao"
   Labels {
    0
   }
  }
  CustomStringTableItem "{5966A779C355A320}" {
   Id "VME-Magazine_QBB81_Description"
   Target_en_us "Magazine loaded with DBP-56 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DBP-56 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio Target Fr Fr."
   Target_de_de "Magazin mit DBP-56-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DBP-56 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DBP-56 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DBP-56 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DBP-56."
   Target_ja_jp "DBP-56 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DBP-56 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DBP-56 de núcleo de aço."
   Target_zh_cn "装有 DBP-56 钢芯弹的弹鼓。"
   Comment "Inventory tooltip for the 45 round 7.62x39mm QBB-81 magazine with steel core cartridges"
   Status TRANSLATION_DONE
   Modified 1500267942
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{C3D2AD00703A9B2E}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBB81_75rnd_Base.et"
  }
  CustomStringTableItem "{5966A77A1DAE8268}" {
   Id "VME-Magazine_QBB81_Name"
   Target_en_us "7.62×39mm 75rnd QBB-81 Mag"
   Target_fr_fr "Chargeur 75 balles QBB-81 7,62 × 39 mm"
   Target_it_it "Caricatore QBB-81 75 colpi 7,62×39 mm"
   Target_de_de "75-Schuss-QBB-81-Magazin. Kaliber 7,62 × 39 mm."
   Target_es_es "Cargador de QBB-81 de 7,62×39 mm, 75 p."
   Target_cs_cz "Zásobník QBB-81, 7,62 × 39 mm, 75 ran"
   Target_pl_pl "75-nab. magazynek 7,62 × 39 mm (QBB-81)"
   Target_ru_ru "Магазин для РПК-74, 75 патр., 7,62×39 мм"
   Target_ja_jp "7.62×39mm 75rnd QBB-81 マガジン"
   Target_ko_kr "7.62×39mm 75발 QBB-81 탄창"
   Target_pt_br "Carregador QBB-81 c/ 75 mun. 7.62×39mm"
   Target_zh_cn "7.62×39 毫米 75 发 QBB-81 弹鼓"
   Comment "UI display name of the 75 round QBB-81 magazine, using 7.62x39mm cartridges"
   Status TRANSLATION_DONE
   Modified 1500267940
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{C3D2AD00703A9B2E}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBB81_75rnd_Base.et"
  }
  CustomStringTableItem "{5966103FC4CF323C}" {
   Id "VME-Magazine_QBZ81_Description"
   Target_en_us "Magazine loaded with DBP-56 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DBP-56 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio DBP-56."
   Target_de_de "Magazin mit DBP-56-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DBP-56 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DBP-56 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DBP-56 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DBP-56."
   Target_ja_jp "DBP-56 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DBP-56 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DBP-56 de núcleo de aço."
   Target_zh_cn "装有 DBP-56 钢芯弹的弹匣。"
   Comment "Inventory tooltip for the default QBZ-81 magazine"
   Status TRANSLATION_DONE
   Modified 1500267937
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{2DB9F84FEAA5C7EA}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBZ81_30rnd_Base.et"
  }
  CustomStringTableItem "{5966103C66759F41}" {
   Id "VME-Magazine_QBZ81_Name"
   Target_en_us "7.62×39mm 30rnd QBZ-81 Mag"
   Target_fr_fr "Chargeur 30 balles QBZ-81 7,62 × 39 mm"
   Target_it_it "Caricatore QBZ-81 30 colpi 7,62×39 mm"
   Target_de_de "30-Schuss-QBZ-81-Magazin. Kaliber 7,62 × 39 mm."
   Target_es_es "Cargador de QBZ-81 de 7,62×39 mm, 30 p."
   Target_cs_cz "Zásobník QBZ-81, 7,62 × 39 mm, 30 ran"
   Target_pl_pl "30-nab. magazynek 7,62 × 39 mm (QBZ-81)"
   Target_ru_ru "Магазин для QBZ-81 на 30 патр., 7,62×39 мм"
   Target_ja_jp "7.62×39mm 30rnd QBZ-81 マガジン"
   Target_ko_kr "7.62×39mm 30발 QBZ-81 탄창"
   Target_pt_br "Carregador QBZ-81 c/ 30 mun. 7.62×39mm"
   Target_zh_cn "7.62×39 毫米 30 发 QBZ-81 弹匣"
   Comment "UI display name of the 30 round QBZ-81 magazine, using 7.62x39mm cartridges"
   Status TRANSLATION_DONE
   Modified 1500267934
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{2DB9F84FEAA5C7EA}Prefabs/Weapons/Magazines/VME_Magazine_762x39_QBZ81_30rnd_Base.et"
  }
  CustomStringTableItem "{596C270A2931476B}" {
   Id "VME-Magazine_QSZ54_Description"
   Target_en_us "Magazine loaded with DAP-51 steel core cartridges."
   Target_fr_fr "Chargeur de cartouches DAP-51 en acier."
   Target_it_it "Caricatore contenente cartucce con anima in acciaio DAP-51."
   Target_de_de "Magazin mit DAP-51-Stahlkernmunition."
   Target_es_es "Cargador con proyectiles DAP-51 con núcleo de acero."
   Target_cs_cz "Zásobník obsahující náboje DAP-51 s ocelovým jádrem."
   Target_pl_pl "Magazynek załadowany nabojami DAP-51 z pociskiem z rdzeniem stalowym."
   Target_ru_ru "Магазин с патронами со стальным сердечником DAP-51."
   Target_ja_jp "DAP-51 スチールコア・カートリッジが装填されたマガジン。"
   Target_ko_kr "DAP-51 철심탄으로 채워진 탄창."
   Target_pt_br "Carregador com cartuchos DAP-51 de núcleo de aço."
   Target_zh_cn "装有 DAP-51 钢芯弹的弹匣。"
   Comment "Inventory tooltip for the QSZ-54 pistol magazine"
   Status TRANSLATION_DONE
   Modified 1500267932
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
  }
  CustomStringTableItem "{596C270AD5E355FA}" {
   Id "VME-Magazine_QSZ54_Name"
   Target_en_us "762x25mm 8rnd QSZ-54 Mag"
   Target_fr_fr "Chargeur 8 balles QSZ-54 762 × 25 mm"
   Target_it_it "Caricatore QSZ-54 8 colpi 762x25 mm"
   Target_de_de "8-Schuss-QSZ-54-Magazin. Kaliber 762 × 25 mm."
   Target_es_es "Cargador de QSZ-54 de 762x25 mm, 8 p."
   Target_cs_cz "Zásobník QSZ-54, 762 × 25 mm, 8 ran"
   Target_pl_pl "8-nab. magazynek 762 × 25 mm (QSZ-54)"
   Target_ru_ru "Магазин для QSZ-54, 8 патр., 762x25 мм"
   Target_ja_jp "762x25mm 8rnd QSZ-54 マガジン"
   Target_ko_kr "762x25mm 8발 QSZ-54 탄창"
   Target_pt_br "Carregador QSZ-54 c/ 8 mun. 762x25mm"
   Target_zh_cn "762x25 毫米 8 发 QSZ-54 弹匣"
   Comment "UI display name of the 8 round 762x25mm QSZ-54 pistol magazine"
   Status TRANSLATION_DONE
   Modified 1500267929
   Author "huhao"
   LastChanged "huhao"
   Labels {
    1100 0
   }
   SourceFile "{98EA3A7DB57F989F}Prefabs/Weapons/Magazines/VME_Magazine_762x25_QSZ54_8rnd_Base.et"
  }
  CustomStringTableItem "{597A2CCACEE294B9}" {
   Id "VME-Weapon_82-2_Description"
   Target_en_us "All plastic handleless steel ball grenade with a 3.5 second timed fuze."
   Target_fr_fr "Grenade à billes en acier sans poignée entièrement en plastique avec une fusée temporisée de 3,5 secondes."
   Target_it_it "Granata a sfera in acciaio senza manico in plastica con una spoletta temporizzata di 3,5 secondi."
   Target_de_de "Ganz aus Kunststoff gefertigte grifflose Stahlkugelgranate mit einem zeitgesteuerten 3,5-Sekunden-Zünder."
   Target_es_es "Granada de bola de acero sin mango de plástico con una espoleta cronometrada de 3,5 segundos."
   Target_cs_cz "Celoplastový ocelový kuličkový granát bez rukojeti s 3,5 sekundovým časovaným zápalníkem."
   Target_pl_pl "Wykonany w całości z tworzywa sztucznego, stalowy granat kulowy bez uchwytu z zapalnikiem z zapalnikiem czasowym 3,5 sekundy."
   Target_ru_ru "Цельнопластиковая стальная шариковая граната без рукоятки с 3,5-секундным взрывателем."
   Target_ja_jp "3.5秒のタイミングの信管を備えたすべてのプラスチック製のハンドルレス鋼球手榴弾。"
   Target_ko_kr "3.5초 시한 신관이 있는 손잡이가 없는 모든 플라스틱 수류탄."
   Target_pt_br "Granada de esfera de aço sem alça de plástico com espoleta cronometrada de 3,5 segundos."
   Target_zh_cn "全塑无柄钢珠手榴弹，设有 3.5 秒的定时引信。"
   Comment "Inventory tooltip for the Type 82-2 grenade - type and fuse"
   Status TRANSLATION_DONE
   Modified 1501193695
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
  }
  CustomStringTableItem "{597A2CCAFEAAB6E0}" {
   Id "VME-Weapon_82-2_Name"
   Target_en_us "82-2"
   Target_fr_fr "82-2"
   Target_it_it "82-2"
   Target_de_de "82-2"
   Target_es_es "82-2"
   Target_cs_cz "82-2"
   Target_pl_pl "82-2"
   Target_ru_ru "82-2"
   Target_ja_jp "82-2"
   Target_ko_kr "82-2"
   Target_pt_br "82-2"
   Target_zh_cn "82-2"
   Comment "Designation of the Type 82-2 grenade, will serve as a display name in the UI"
   Status TRANSLATION_DONE
   Modified 1501193589
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
  }
  CustomStringTableItem "{5966A77EA8EBE3B2}" {
   Id "VME-Weapon_QBB81_Description"
   Target_en_us "7.62×39mm light machine gun."
   Target_fr_fr "Mitrailleuse légère 7,62 × 39 mm."
   Target_it_it "Mitragliatrice leggera da 7,62×39 mm."
   Target_de_de "Leichtes Maschinengewehr im Kaliber 7,62 × 39 mm."
   Target_es_es "Ametralladora ligera de 7,62×39 mm."
   Target_cs_cz "Lehký kulomet ráže 7,62 × 39 mm."
   Target_pl_pl "Lekki karabin maszynowy 7,62 × 39 mm."
   Target_ru_ru "Легкий пулемет 7,62×39 мм."
   Target_ja_jp "7.62×39mm 軽機関銃。"
   Target_ko_kr "7.62×39mm 경기관총."
   Target_pt_br "Metralhadora leve 7.62×39mm."
   Target_zh_cn "7.62×39mm 班用机枪。"
   Status TRANSLATION_DONE
   Modified 1500267927
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{D00F9E62E98B41BB}Prefabs/Weapons/MachineGuns/QBB81/VME_MG_QBB81.et"
  }
  CustomStringTableItem "{5966A77EB61DCAB5}" {
   Id "VME-Weapon_QBB81_Name"
   Target_en_us "QBB-81"
   Target_fr_fr "QBB-81"
   Target_it_it "QBB-81"
   Target_de_de "QBB-81"
   Target_es_es "QBB-81"
   Target_cs_cz "QBB-81"
   Target_pl_pl "QBB-81"
   Target_ru_ru "QBB-81"
   Target_ja_jp "QBB-81"
   Target_ko_kr "QBB-81"
   Target_pt_br "QBB-81"
   Target_zh_cn "QBB-81"
   Comment "Designation of the QBB-81"
   Status TRANSLATION_DONE
   Modified 1500267924
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{D00F9E62E98B41BB}Prefabs/Weapons/MachineGuns/QBB81/VME_MG_QBB81.et"
  }
  CustomStringTableItem "{5966103997F423F1}" {
   Id "VME-Weapon_QBZ81-1_Description"
   Target_en_us "7.62×39mm assault rifle."
   Target_fr_fr "Fusil d'assaut de calibre 7,62 × 39 mm."
   Target_it_it "Fucile d’assalto da 7,62×39 mm."
   Target_de_de "Sturmgewehr im Kaliber 7,62 × 39 mm."
   Target_es_es "Fusil de asalto de 7,62×39 mm."
   Target_cs_cz "Útočná puška ráže 7,62 × 39 mm."
   Target_pl_pl "Karabinek automatyczny 7,62 × 39 mm."
   Target_ru_ru "Штурмовая винтовка 7,62×39 мм."
   Target_ja_jp "7.62×39mm アサルトライフル。"
   Target_ko_kr "7.62×39mm 돌격소총."
   Target_pt_br "Fuzil de assalto 7.62×39mm."
   Target_zh_cn "7.62×39mm 自动步枪。"
   Comment "Inventory tooltip for the QBZ-81 assault rifle - caliber and weapon type"
   Status TRANSLATION_DONE
   Modified 1500267921
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{E4672CFB06A4E556}Prefabs/Weapons/Rifles/QBZ81/VME_Rifle_QBZ81-1.et"
  }
  CustomStringTableItem "{59661039B274A3A6}" {
   Id "VME-Weapon_QBZ81-1_Name"
   Target_en_us "QBZ-81-1"
   Target_fr_fr "QBZ-81-1"
   Target_it_it "QBZ-81-1"
   Target_de_de "QBZ-81-1"
   Target_es_es "QBZ-81-1"
   Target_cs_cz "QBZ-81-1"
   Target_pl_pl "QBZ-81-1"
   Target_ru_ru "QBZ-81-1"
   Target_ja_jp "QBZ-81-1"
   Target_ko_kr "QBZ-81-1"
   Target_pt_br "QBZ-81-1"
   Target_zh_cn "QBZ-81-1"
   Comment "Designation of the QBZ81-1 assault rifle, will serve as a display name in the UI"
   Status TRANSLATION_DONE
   Modified 1500267918
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{E4672CFB06A4E556}Prefabs/Weapons/Rifles/QBZ81/VME_Rifle_QBZ81-1.et"
  }
  CustomStringTableItem "{596C271400CCE2DB}" {
   Id "VME-Weapon_QSZ54_Description"
   Target_en_us "762×22mm semi-automatic pistol."
   Target_fr_fr "Pistolet semi-automatique de calibre 762 × 22 mm."
   Target_it_it "Pistola semi-automatica da 762×22 mm."
   Target_de_de "Halbautomatik-Pistole im Kaliber 762×22mm."
   Target_es_es "Pistola semiautomática de 762×22 mm."
   Target_cs_cz "Poloautomatická pistole ráže 762 × 22 mm."
   Target_pl_pl "Pistolet samopowtarzalny 762 × 22 mm."
   Target_ru_ru "Полуавтоматический пистолет 762×22 мм."
   Target_ja_jp "セミオートマチックの 762×22mm ピストル。"
   Target_ko_kr "762×22mm 반자동권총."
   Target_pt_br "Pistola semiautomática 762×22mm."
   Target_zh_cn "762×22mm 半自动手枪。"
   Comment "Inventory tooltip for the QSZ-54 pistol - caliber, action and weapon type"
   Status TRANSLATION_DONE
   Modified 1500268805
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{EE18912DBDDDB6C7}Prefabs/Weapons/Handguns/QSZ54/VME_Handgun_QSZ54.et"
  }
  CustomStringTableItem "{596C271423EA46E7}" {
   Id "VME-Weapon_QSZ54_Name"
   Target_en_us "QSZ-54"
   Target_fr_fr "QSZ-54"
   Target_it_it "QSZ-54"
   Target_de_de "QSZ-54"
   Target_es_es "QSZ-54"
   Target_cs_cz "QSZ-54"
   Target_pl_pl "QSZ-54"
   Target_ru_ru "QSZ-54"
   Target_ja_jp "QSZ-54"
   Target_ko_kr "QSZ-54"
   Target_pt_br "QSZ-54"
   Target_zh_cn "QSZ-54"
   Comment "Designation of the QSZ-54 handgun, will serve as a display name in the UI"
   Status TRANSLATION_DONE
   Modified 1500268800
   Author "huhao"
   LastChanged "huhao"
   Labels {
    2 0
   }
   SourceFile "{EE18912DBDDDB6C7}Prefabs/Weapons/Handguns/QSZ54/VME_Handgun_QSZ54.et"
  }
 }
}